# Generated by Django 3.2.22 on 2023-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_sitedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='total_posts_created',
            field=models.IntegerField(default=0),
        ),
    ]
