# Generated by Django 3.2.22 on 2023-12-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='category',
        ),
    ]
