# Generated by Django 3.2.22 on 2023-12-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20231210_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='category',
        ),
    ]
