# Generated by Django 3.2.22 on 2023-12-14 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0017_remove_poll_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to='forum.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='forum.post')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
