# Generated by Django 3.2.22 on 2023-12-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_report_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
