# Generated by Django 3.2.22 on 2023-12-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_delete_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='penalty_points',
        ),
    ]
