# Generated by Django 3.2.22 on 2024-01-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_remove_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
